// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace EosGameplayTags
{
	/** Input Tags **/
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Inventory);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Dash);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Guard);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipWeapon);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipWeapon);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Guard_Hold);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggle);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggle_TargetLock);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SwitchTarget);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_FocusOnChat);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Continue);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Continue_Skill_E);

	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill_Q);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill_E);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill_R);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill_F);

	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_QuickSlot_1);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_QuickSlot_2);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_QuickSlot_3);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_QuickSlot_4);

	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_GreatSword);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SmashAttack_GreatSword);

	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Healer);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SmashAttack_Healer);

	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SmashAttack_Lancer);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Lancer);

	/** Weapon Tags : Player **/
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_GreatSword);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Staff);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Lance);

	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_EquipWeapon);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_UnequipWeapon);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_GuardSuccess);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTarget_Left);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTarget_Right);

	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Spawn_Right);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Spawn_Left);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Spawn_TwoHands);

	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Skill_GreatSword_PowerLevel1);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Skill_GreatSword_PowerLevel2);

	/** Weapon Tags : Enemy **/
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon_Hammer);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon_Sword);

	/** Player Ability Tags **/
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_GreatSword);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Smash_GreatSword);

	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Healer);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Smash_Healer);

	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Lancer);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Smash_Lancer);

	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Dash);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Guarding);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_TargetLock);

	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Skill_Q);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Skill_E);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Skill_R);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Skill_F);

	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Items_Potion);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Items_Artifact);

	/** Player Status Tags **/
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Weapon_Equip);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Weapon_Unequip);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Light_Combo1);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Light_Combo2);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Light_Combo3);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Light_Combo4);
	//PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Light_Combo5);
	//PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Light_Combo6);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Smash_InProgress);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Smash_EndProgress);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Smash_Extend);

	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Counter);

	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Dash);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Guarding);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_TargetLock);

	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_SuperArmor);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Invincibility);

	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_GreatSword_StackDash);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_GreatSword_Ironwall);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_GreatSword_Revengeable);

	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Items_UsingPotion);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Items_UsingArtifact);

	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_InCombat);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_OpenMenu);

	/** Player Event Tags **/
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Combo_Start);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Combo_End);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Smash_Extended);

	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_React_CameraShake);

	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_GreatSword_ActivateIronwall);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_GreatSword_SuccessIronwall);

	/** Player SetByCaller Tags **/
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Smash);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Skill);

	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_Status_Stamina);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_Status_Mana);
	//PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_Status_Identity);

	/** Player Cooldown Tags **/
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Cooldown_Skill_Q);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Cooldown_Skill_E);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Cooldown_Skill_R);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Cooldown_Skill_F);

	/** Enemy Ability Tags **/
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Combo);

	/** Enemy Boss Ability Tags **/
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Boss_PrePhase_Melee);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Boss_PrePhase_Combo);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Boss_Phase1_Melee);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Boss_Phase1_Combo);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Boss_Phase1_PhaseSkill);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Boss_Phase1_Skill);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Boss_Phase2_Melee);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Boss_Phase2_Combo);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Boss_Phase2_PhaseSkill);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Boss_Phase2_Skill);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Boss_Phase3_Melee);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Boss_Phase3_Combo);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Boss_Phase3_PhaseSkill);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Boss_Phase3_Skill);

	/** Enemy Status Tags **/
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Strafing);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Stunned);

	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_BreakGuard);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Counterable);

	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_UnderAttack);

	/** Enemy Boss Status Tags **/
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Boss);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Boss_PrePhase);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Boss_Phase1);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Boss_Phase2);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Boss_Phase3);

	/** Enemy Event Tags **/
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_SuccessCounter);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_Summoning);

	/** Enemy Boss Event Tags **/
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_Boss_PrePhase);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_Boss_Phase1);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_Boss_Phase2);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_Boss_Phase3);
	
	/** Common Ability Tags **/
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Ability_Dead);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Ability_HitReact);

	/** Common Status Tags **/
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Status_HitReact_Front);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Status_HitReact_Left);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Status_HitReact_RIght);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Status_HitReact_Back);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Status_Dead);

	/** Common Event Tags **/
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Event_MeleeHit);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Event_RangeHit);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Event_SkillSpawn);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Event_HitReact_Light);
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_Event_HitReact_Heavy);

	/** Common SetByCaller Tags **/
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Common_SetByCaller_BaseDamage);

	/** GameplayCur Tags **/
	PROJECTEOS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Feedback_HoldAnim);
}
